comment_width = 120
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
wrap_comments = true