[web]
port = 9999

[mongo]
host = "192.168.8.127"
port = "27017"
user = "mongo_FpaAJZ"
password = "mongo_KZAKYi"
db_name = "blog"


[logger]
enable = true                           # 是否启用日志功能，默认是开启的
pretty_backtrace = false                    # 是否打印堆栈信息，默认是关闭的，建议只在应用开发阶段开启
level = "info"                              # 默认日志级别是info
format = "compact"                          # 日志格式支持compact、pretty、json，默认是compact
time_style = "local"
time_pattern = "|%Y-%m-%d %H:%M:%S|"         # 时间戳的输出格式，time_style为local、utc时才生效
with_fields = [# 输出日志时携带其他字段，默认不携带以下字段
    "thread_id", # 当前线程ID
    "thread_name", # 当前线程名
    "file", # 输出该日志的源文件名字
    "line_number", # 输出该日志的源文件所在行号
    "internal_errors", # 当出现错误时是否输出包含的内部错误
]
override_filter = "info,axum=warn,web=debug"         # 重写默认的日志过滤级别，可以针对crate库指定日志级别
[logger.file]
enable = true                              # 是否将日志写入文件
non_blocking = true                         # 是否启用非阻塞方式写入，默认开启
format = "compact"                          # 日志格式支持compact、pretty、json，默认是compact
rotation = "daily"                          # 日志滚动方式minutely、hourly、daily、never，默认按天滚动
dir = "./logs"                              # 日志文件目录
filename_prefix = "app"                     # 日志文件前缀名
filename_suffix = "log"                     # 日志文件后缀名
max_log_files = 365                         # 保留的最大日志数量